import { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { Terminal, Copy, Download, FileJson2, CheckSquare, Square } from 'lucide-react'
import UtilityModal from './UtilityModal.jsx'
import { showToast } from '../../utils/toast'
import { copyText } from '../../utils/copy'

const APP_GROUPS = [
  {
    label: 'Browsers & Media',
    apps: [
      { id: 'chrome', label: 'Google Chrome', winget: 'Google.Chrome', choco: 'googlechrome' },
      { id: 'firefox', label: 'Mozilla Firefox', winget: 'Mozilla.Firefox', choco: 'firefox' },
      { id: 'vlc', label: 'VLC Media Player', winget: 'VideoLAN.VLC', choco: 'vlc' },
      { id: 'spotify', label: 'Spotify', winget: 'Spotify.Spotify', choco: 'spotify' },
      { id: 'obs', label: 'OBS Studio', winget: 'OBSProject.OBSStudio', choco: 'obs-studio' },
      { id: 'discord', label: 'Discord', winget: 'Discord.Discord', choco: 'discord' },
    ],
  },
  {
    label: 'Development',
    apps: [
      { id: 'vscode', label: 'VS Code', winget: 'Microsoft.VisualStudioCode', choco: 'vscode' },
      { id: 'git', label: 'Git', winget: 'Git.Git', choco: 'git' },
      { id: 'node', label: 'Node.js LTS', winget: 'OpenJS.NodeJS.LTS', choco: 'nodejs-lts' },
      { id: 'python', label: 'Python 3', winget: 'Python.Python.3.12', choco: 'python' },
      { id: 'mingw', label: 'MinGW (C/C++)', winget: 'BrechtSanders.WinLibs.POSIX.UCRT', choco: 'mingw' },
    ],
  },
  {
    label: 'Productivity',
    apps: [
      { id: 'notion', label: 'Notion', winget: 'Notion.Notion', choco: 'notion' },
      { id: 'obsidian', label: 'Obsidian', winget: 'Obsidian.Obsidian', choco: 'obsidian' },
      { id: 'powertoys', label: 'Microsoft PowerToys', winget: 'Microsoft.PowerToys', choco: 'powertoys' },
      { id: 'everything', label: 'Everything Search', winget: 'voidtools.Everything', choco: 'everything' },
    ],
  },
  {
    label: 'Essentials',
    apps: [
      { id: '7zip', label: '7-Zip', winget: '7zip.7zip', choco: '7zip.install' },
      { id: 'winrar', label: 'WinRAR', winget: 'RARLab.WinRAR', choco: 'winrar' },
    ],
  },
]

const TWEAKS = [
  { id: 'dnscache', label: 'Flush DNS cache', line: 'ipconfig /flushdns' },
  { id: 'cleantemp', label: 'Clear temp folders', line: 'Remove-Item "$env:TEMP\\*" -Recurse -Force -ErrorAction SilentlyContinue' },
  { id: 'hibernate', label: 'Disable hibernation', line: 'powercfg /hibernate off' },
  { id: 'hiddenfiles', label: 'Show hidden files & folders', line: "Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced' -Name Hidden -Value 1 -Force" },
  { id: 'powerplan', label: 'High-performance power plan', line: 'powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c' },
]

function buildScript(manager, appIds, tweakIds) {
  const stamp = new Date().toLocaleString()
  const apps = APP_GROUPS.flatMap((g) => g.apps).filter((a) => appIds.has(a.id))
  const lines = []

  lines.push('# ==============================================')
  lines.push('#  Auto-generated install script')
  lines.push('#  Generated by  : jmshakya.com.np')
  lines.push(`#  Generated on  : ${stamp}`)
  lines.push(`#  Installer     : ${manager === 'choco' ? 'Chocolatey (auto-installed)' : 'winget (built-in)'}`)
  lines.push('# ==============================================')
  lines.push('')
  lines.push("$ErrorActionPreference = 'Stop'")

  if (manager === 'choco') {
    lines.push('')
    lines.push("# Ensure Chocolatey is present")
    lines.push("if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {")
    lines.push("  Set-ExecutionPolicy Bypass -Scope Process -Force")
    lines.push("  [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072")
    lines.push("  Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))")
    lines.push("}")
  }

  if (apps.length) {
    const ids = apps.map((a) => (manager === 'choco' ? a.choco : a.winget))
    lines.push('')
    lines.push(`Write-Host " > Installing ${apps.length} package(s)..." -ForegroundColor Cyan`)
    lines.push(`$apps = @(${ids.map((i) => `'${i}'`).join(', ')})`)
    lines.push('')
    lines.push('foreach ($app in $apps) {')
    lines.push('  Write-Host ("`n  [" + $app + "] installing...") -NoNewline')
    if (manager === 'choco') {
      lines.push('  choco install $app -y --no-progress')
    } else {
      lines.push('  winget install --exact --id $app --silent --accept-package-agreements --accept-source-agreements')
    }
    lines.push('  if ($LASTEXITCODE -ne 0) { Write-Warning "  `n  Failed: $app" }')
    lines.push('}')
  }

  if (tweakIds.size) {
    const tweaks = TWEAKS.filter((t) => tweakIds.has(t.id))
    lines.push('')
    lines.push('# System tweaks')
    tweaks.forEach((t) => lines.push(t.line))
  }

  lines.push('')
  lines.push("Write-Host '`n > All done. Press any key to exit...' -ForegroundColor Green")
  lines.push("$null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')")
  return lines.join('\n')
}

export default function PsBuilderModal({ onClose }) {
  const [manager, setManager] = useState('winget')
  const [appIds, setAppIds] = useState(() => new Set(['chrome', 'vlc', 'vscode', '7zip']))
  const [tweakIds, setTweakIds] = useState(() => new Set(['dnscache']))

  const toggle = (set, id, setter) => {
    const next = new Set(set)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    setter(next)
  }

  const script = useMemo(() => buildScript(manager, appIds, tweakIds), [manager, appIds, tweakIds])

  const allAppCount = APP_GROUPS.flatMap((g) => g.apps).length

  const downloadScript = () => {
    const blob = new Blob(['\uFEFF' + script], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `setup-${appIds.size}-apps.ps1`
    document.body.appendChild(a)
    a.click()
    a.remove()
    URL.revokeObjectURL(url)
    showToast(`setup-${appIds.size}-apps.ps1 downloaded`)
  }

  const copyScript = async () => {
    await copyText(script)
    showToast('PowerShell script copied', { kind: 'copy', description: `setup-${appIds.size}-apps.ps1` })
  }

  return (
    <UtilityModal title="Quick PowerShell Script Builder" subtitle="check apps → generate → run as admin" onClose={onClose} wide>
      <div className="grid lg:grid-cols-2 gap-6">
        <div>
          <div className="flex items-center gap-2 mb-4">
            <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-neon-cyan/10 border border-neon-cyan/30">
              <Terminal className="w-4 h-4 text-neon-cyan" />
            </span>
            <h4 className="text-sm font-bold text-white">1 · Pick a package manager</h4>
          </div>
          <div className="grid grid-cols-2 gap-2 mb-6">
            <button
              onClick={() => setManager('winget')}
              className={`px-4 py-3 rounded-xl text-sm font-semibold border transition-all duration-300 ${manager === 'winget' ? 'bg-neon-cyan/15 border-neon-cyan/60 text-white' : 'bg-white/[0.03] border-white/10 text-white/50 hover:text-white'}`}
            >
              winget · built-in
              <span className="block text-[10px] font-mono text-white/35 mt-0.5">Windows 10/11</span>
            </button>
            <button
              onClick={() => setManager('choco')}
              className={`px-4 py-3 rounded-xl text-sm font-semibold border transition-all duration-300 ${manager === 'choco' ? 'bg-neon-violet/15 border-neon-violet/60 text-white' : 'bg-white/[0.03] border-white/10 text-white/50 hover:text-white'}`}
            >
              chocolatey
              <span className="block text-[10px] font-mono text-white/35 mt-0.5">auto-installs if missing</span>
            </button>
          </div>

          <div className="flex items-center justify-between mb-3">
            <h4 className="text-sm font-bold text-white flex items-center gap-2">
              <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-neon-violet/10 border border-neon-violet/30">
                <CheckSquare className="w-4 h-4 text-neon-violet" />
              </span>
              2 · Select software
            </h4>
            <span className="text-[11px] font-mono text-white/40">{appIds.size} / {allAppCount} selected</span>
          </div>

          <div className="space-y-4 max-h-56 overflow-y-auto pr-1">
            {APP_GROUPS.map((g) => (
              <div key={g.label}>
                <p className="text-[10px] font-mono uppercase tracking-widest text-white/40 mb-2">{g.label}</p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5">
                  {g.apps.map((a) => {
                    const on = appIds.has(a.id)
                    return (
                      <button
                        key={a.id}
                        onClick={() => toggle(appIds, a.id, setAppIds)}
                        className={`flex items-center gap-2.5 px-3 py-2.5 rounded-xl text-xs font-medium border transition-all duration-200 ${
                          on
                            ? 'bg-gradient-to-r from-neon-cyan/15 to-neon-violet/15 border-neon-cyan/50 text-white'
                            : 'bg-white/[0.03] border-white/10 text-white/55 hover:border-white/30 hover:text-white'
                        }`}
                      >
                        <span className={`flex h-4.5 w-4.5 h-5 w-5 items-center justify-center rounded border transition-colors ${on ? 'bg-neon-cyan border-neon-cyan' : 'border-white/40'}`}>
                          {on && <CheckSquare className="w-3.5 h-3.5 text-[#05050a]" />}
                        </span>
                        {a.label}
                      </button>
                    )
                  })}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-6">
            <h4 className="text-sm font-bold text-white mb-3 flex items-center gap-2">
              <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-neon-fuchsia/10 border border-neon-fuchsia/30">
                <FileJson2 className="w-4 h-4 text-neon-fuchsia" />
              </span>
              3 · System tweaks
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5">
              {TWEAKS.map((t) => {
                const on = tweakIds.has(t.id)
                return (
                  <button
                    key={t.id}
                    onClick={() => toggle(tweakIds, t.id, setTweakIds)}
                    className={`flex items-center gap-2.5 px-3 py-2.5 rounded-xl text-xs font-medium border transition-all duration-200 ${
                      on
                        ? 'bg-gradient-to-r from-neon-fuchsia/15 to-neon-violet/15 border-neon-fuchsia/50 text-white'
                        : 'bg-white/[0.03] border-white/10 text-white/55 hover:border-white/30 hover:text-white'
                    }`}
                  >
                    <span className={`flex h-5 w-5 items-center justify-center rounded border transition-colors ${on ? 'bg-neon-fuchsia border-neon-fuchsia' : 'border-white/40'}`}>
                      {on && <Square className="w-3 h-3 text-[#05050a]" />}
                    </span>
                    {t.label}
                  </button>
                )
              })}
            </div>
          </div>
        </div>

        <div className="flex flex-col min-h-0">
          <div className="flex items-center justify-between mb-4">
            <h4 className="text-sm font-bold text-white flex items-center gap-2">
              <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-400/10 border border-emerald-400/30">
                <Terminal className="w-4 h-4 text-emerald-400" />
              </span>
              Live preview
            </h4>
            <span className="text-[11px] font-mono text-white/40">{script.split('\n').length} lines</span>
          </div>

          <pre className="flex-1 bg-base-950/80 border border-white/10 rounded-xl p-4 text-[11px] font-mono leading-relaxed text-white/80 overflow-auto max-h-80 lg:max-h-none select-text whitespace-pre">
{script}
          </pre>

          <div className="flex flex-col sm:flex-row gap-2.5 mt-4">
            <motion.button
              whileTap={{ scale: 0.97 }}
              onClick={copyScript}
              className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-3 rounded-xl text-sm font-bold text-white bg-gradient-to-r from-neon-cyan/20 to-neon-violet/20 border border-neon-cyan/40 hover:shadow-[0_0_25px_rgba(0,240,255,0.25)] transition-all duration-300"
            >
              <Copy className="w-4 h-4 text-neon-cyan" /> Copy Script
            </motion.button>
            <motion.button
              whileTap={{ scale: 0.97 }}
              onClick={downloadScript}
              disabled={script.length < 20}
              className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-3 rounded-xl text-sm font-bold text-emerald-300 bg-emerald-500/10 border border-emerald-400/40 hover:bg-emerald-500/20 hover:shadow-[0_0_25px_rgba(52,211,153,0.2)] transition-all duration-300 disabled:opacity-40"
            >
              <Download className="w-4 h-4 text-emerald-400" /> Download .ps1
            </motion.button>
          </div>

          <p className="mt-3 text-[11px] font-mono text-white/40 text-center">
            Save as .ps1 → right-click → <span className="text-emerald-400">Run with PowerShell</span>
          </p>
        </div>
      </div>
    </UtilityModal>
  )
}